import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ContactForm, PerformanceProbe, RfqForm, SelfTest, StatusTools } from "@/components/Interactive";
import { jobBySlug, jobs, productBySlug, products, type Product } from "@/lib/data";
import { featureFlags, isProduction, labModules, SITE_NAME, SITE_URL } from "@/lib/site";

type PageProps = {
  params: Promise<{ slug?: string[] }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
};

const pathOf = (slug?: string[]) => `/${(slug || []).join("/")}`.replace(/\/$/, "") || "/";
const canonical = (path: string) => `${SITE_URL}${path === "/" ? "" : path}`;

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const path = pathOf(slug);
  if (path === "/") return { title: { absolute: SITE_NAME }, alternates: { canonical: SITE_URL } };
  if (path.startsWith("/lab")) return { title: path === "/lab" ? "Lab" : path.split("/").pop()!.replaceAll("-", " "), robots: { index: false, follow: false, nocache: true } };
  if (path === "/products") return { title: "Products", description: "Engineered product systems, specifications and quote-ready detail pages.", alternates: { canonical: canonical(path) }, openGraph: { title: `Products | ${SITE_NAME}`, description: "Explore engineered product systems and specifications.", url: canonical(path) } };
  if (path === "/careers") return { title: "Careers", description: "Explore open roles across digital, commercial, platform and customer teams.", alternates: { canonical: canonical(path) }, openGraph: { title: `Careers | ${SITE_NAME}`, description: "Explore open roles and how we work.", url: canonical(path) } };
  if (path === "/contact") return { title: "Contact", alternates: { canonical: canonical(path) } };
  if (path === "/rfq") return { title: "Request Quote", alternates: { canonical: canonical(path) } };
  if (slug?.[0] === "products" && slug[1]) {
    const product = productBySlug(slug[1]);
    if (product) return { title: `${product.name} (${product.partNumber})`, description: product.summary, alternates: { canonical: canonical(path) }, openGraph: { title: product.name, description: product.summary, url: canonical(path) } };
  }
  if (slug?.[0] === "careers" && slug[1]) {
    const job = jobBySlug(slug[1]);
    if (job) return { title: job.title, description: job.summary, alternates: { canonical: canonical(path) }, openGraph: { title: job.title, description: job.summary, url: canonical(path) } };
  }
  return { title: "Not Found", robots: { index: false } };
}

function JsonLd({ value }: { value: unknown }) { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(value) }} />; }
function ProductCard({ product }: { product: Product }) {
  return <article className="productCard"><div className="productImage"><Image src={product.image} alt={product.imageAlt} fill sizes="(max-width: 940px) 50vw, 33vw" /></div><div className="productBody"><div className="productMeta"><span>{product.category}</span><span>{product.partNumber}</span></div><h2>{product.name}</h2><p>{product.summary}</p><Link className="textLink" href={`/products/${product.slug}`}>Explore system â†’</Link></div></article>;
}
function LabNav() { return <nav className="labnav" aria-label="Lab navigation"><Link href="/lab">Lab Home</Link>{labModules.map((module) => <Link href={`/lab/${module}`} key={module}>{module.replaceAll("-", " ")}</Link>)}</nav>; }
function PageHero({ eyebrow, title, lede }: { eyebrow: string; title: string; lede: string }) { return <section className="hero compact"><div className="shell"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="lede">{lede}</p></div></section>; }

export default async function Page({ params, searchParams }: PageProps) {
  const { slug } = await params;
  const query = await searchParams;
  const path = pathOf(slug);
  const production = isProduction();

  if (path === "/") return <main id="main-content"><JsonLd value={{ "@context": "https://schema.org", "@type": "WebSite", name: SITE_NAME, url: `${SITE_URL}/` }} /><section className="heroEditorial"><div className="shell heroGrid"><div className="heroCopy"><span className="eyebrow">Industrial systems Â· digital operations</span><h1>Built to make complex work feel considered.</h1><p className="lede">A refined reference experience for product discovery, careers and the Vercel systems behind reliable delivery.</p><div className="actions"><Link className="button" href="/products">Explore products</Link><Link className="button secondary" href="/careers">View open roles</Link></div></div><figure className="heroMedia"><Image src={products[0].image} alt="Contemporary curved metal architecture" fill priority sizes="(max-width: 940px) 100vw, 58vw" /><figcaption className="heroCaption">Architecture study Â· material, rhythm, restraint</figcaption></figure></div></section><section className="statBar"><div className="shell stats"><div className="stat"><strong>03</strong><span>Engineered product systems</span></div><div className="stat"><strong>06</strong><span>Open roles across multiple teams</span></div><div className="stat"><strong>07</strong><span>Technical Lab modules</span></div></div></section><section className="section"><div className="shell"><div className="sectionHead"><div><span className="kicker">Selected systems</span><h2>Products with context, not clutter.</h2></div><p>Clear specifications, restrained visuals and a quote flow that carries the product forward automatically.</p></div><div className="grid three">{products.map((product) => <ProductCard product={product} key={product.slug} />)}</div></div></section><section className="section sectionTint"><div className="shell featureSplit"><div className="mediaFrame"><Image src={products[2].image} alt="Modern atrium and workplace architecture" fill sizes="(max-width: 940px) 100vw, 50vw" /></div><div><span className="kicker">Careers</span><p className="quote">Good systems are built by people who care about the details nobody else sees.</p><p className="lede">Explore roles spanning product, platform, commercial and operations work.</p><div className="actions"><Link className="button" href="/careers">Explore careers</Link></div></div></div></section></main>;

  if (path === "/products") return <main id="main-content"><PageHero eyebrow="Engineered systems" title="Products built around real constraints." lede="Three product systems with clear specifications, intended uses and direct quote handoff." /><section className="section"><div className="shell grid three">{products.map((product) => <ProductCard product={product} key={product.slug} />)}</div></section><section className="ctaBand"><div className="shell"><span className="kicker">Commercial support</span><p className="quote">Know what you need, or still working it out?</p><p className="lede">Start a quote request with a product selected, then add project context.</p><div className="actions"><Link className="button secondary" href="/rfq">Request Quote</Link></div></div></section></main>;

  if (slug?.[0] === "products" && slug[1] && slug.length === 2) {
    const product = productBySlug(slug[1]); if (!product) notFound();
    const related = product.related.map(productBySlug).filter(Boolean) as Product[];
    return <main id="main-content"><JsonLd value={{ "@context": "https://schema.org", "@type": "Product", name: product.name, sku: product.partNumber, category: product.category, description: product.summary, url: canonical(path) }} /><section className="section"><div className="shell detailGrid"><div className="detailCopy"><span className="eyebrow">{product.category} Â· {product.status}</span><h1>{product.name}</h1><p className="lede">{product.summary}</p><div className="roleMeta"><span className="pill">{product.partNumber}</span><span className="pill">Quote ready</span></div><div className="actions"><Link className="button" href={`/rfq?product=${product.slug}`}>Request Quote</Link><Link className="button secondary" href="/products">Back to products</Link></div></div><div className="detailImage"><Image src={product.image} alt={product.imageAlt} fill priority sizes="(max-width: 940px) 100vw, 55vw" /></div></div></section><section className="section sectionTint"><div className="shell specGrid"><div className="card"><span className="kicker">Specifications</span><h2>System detail</h2>{Object.entries(product.specs).map(([key, value]) => <div className="row" key={key}><span>{key}</span><strong>{value}</strong></div>)}</div><div className="card"><span className="kicker">Applications</span><h2>Designed for</h2><ul>{product.uses.map((use) => <li key={use}>{use}</li>)}</ul><h3>Reference documents</h3><ul>{product.downloads.map((download) => <li key={download}>{download} <span className="muted">(demo reference)</span></li>)}</ul></div></div></section><section className="section"><div className="shell"><div className="sectionHead"><div><span className="kicker">Related systems</span><h2>Continue exploring.</h2></div></div><div className="grid two">{related.map((item) => <ProductCard product={item} key={item.slug} />)}</div></div></section></main>;
  }

  if (path === "/careers") return <main id="main-content"><section className="careerHero"><div className="careerHeroCopy"><span className="eyebrow">Career Center</span><h1>Work on systems people can trust.</h1><p className="lede">Join teams shaping product experiences, digital operations, commercial systems and reliability.</p></div><div className="careerMedia"><Image src={products[2].image} alt="Modern collaborative architectural space" fill priority sizes="(max-width: 940px) 100vw, 50vw" /></div></section><section className="section"><div className="shell"><div className="sectionHead"><div><span className="kicker">Open roles</span><h2>Six places to make an impact.</h2></div><p>The listings are demonstration content for this learning project. A secure ATS connection is intentionally deferred.</p></div><div className="careerList">{jobs.map((job) => <Link className="careerRow" href={`/careers/${job.slug}`} key={job.slug}><strong>{job.title}</strong><span>{job.team}</span><span>{job.location}</span><b>â†’</b></Link>)}</div></div></section><section className="section sectionTint"><div className="shell grid three"><div className="card"><span className="kicker">01</span><h2>Own the detail</h2><p>Quality lives in the small decisions that compound across a system.</p></div><div className="card"><span className="kicker">02</span><h2>Work across boundaries</h2><p>Product, engineering, operations and commercial teams solve better problems together.</p></div><div className="card"><span className="kicker">03</span><h2>Ship responsibly</h2><p>Preview first, observe real behavior, then promote with confidence.</p></div></div></section></main>;

  if (slug?.[0] === "careers" && slug[1] && slug.length === 2) {
    const job = jobBySlug(slug[1]); if (!job) notFound();
    const remote = job.location.toLowerCase().includes("remote");
    return <main id="main-content"><JsonLd value={{ "@context": "https://schema.org", "@type": "JobPosting", title: job.title, description: job.summary, employmentType: "FULL_TIME", hiringOrganization: { "@type": "Organization", name: SITE_NAME, sameAs: SITE_URL }, ...(remote ? { jobLocationType: "TELECOMMUTE" } : { jobLocation: { "@type": "Place", address: { "@type": "PostalAddress", addressLocality: job.location } } }) }} /><section className="section"><div className="shell detailGrid"><div className="detailCopy"><span className="eyebrow">{job.team} Â· {job.type}</span><h1>{job.title}</h1><p className="lede">{job.summary}</p><div className="roleMeta"><span className="pill">{job.location}</span><span className="pill">{job.type}</span></div><div className="actions"><Link className="button secondary" href="/careers">Back to careers</Link></div></div><div className="card"><span className="kicker">Application status</span><h2>ATS connection deferred</h2><p>Application handling is intentionally not simulated. A secure ATS integration is the next phase for a real apply flow.</p></div></div></section><section className="section sectionTint"><div className="shell specGrid"><div className="card"><span className="kicker">What you will do</span><h2>Responsibilities</h2><ul>{job.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="card"><span className="kicker">Core strengths</span><h2>What helps</h2><ul>{job.strengths.map((item) => <li key={item}>{item}</li>)}</ul></div></div></section></main>;
  }

  if (path === "/contact") return <main id="main-content"><PageHero eyebrow="Contact" title="Start with the problem." lede="Tell us what you are trying to solve. The form is validated, size-limited and protected against basic automated abuse." /><section className="section"><div className="shell specGrid"><div><span className="kicker">General inquiry</span><p className="quote">Clear context makes the next conversation better.</p><p className="lede">Requests are acknowledged by the demo API but are not persisted or emailed yet.</p></div><ContactForm /></div></section></main>;

  if (path === "/rfq") {
    const initial = typeof query.product === "string" ? query.product : undefined;
    return <main id="main-content"><PageHero eyebrow="Request Quote" title="Bring the project into focus." lede="If you arrived from a product detail page, that system is already selected for you." /><section className="section"><div className="shell specGrid"><div><span className="kicker">Quote workflow</span><p className="quote">Product first. Project context second.</p><p className="lede">The request is validated and acknowledged without pretending a CRM is connected.</p></div><RfqForm initial={initial} /></div></section></main>;
  }

  if (path.startsWith("/lab")) {
    const labModule = slug?.[1];
    const env = process.env.VERCEL_ENV || "development";
    if (!labModule) return <><LabNav /><main id="main-content"><PageHero eyebrow="Technical Lab Â· noindex" title="Engineering behavior, kept out of the public story." lede="Deployment, observability, environment behavior, feature flags, performance and error handling in one controlled area." /><section className="section"><div className="shell grid three">{labModules.map((item, index) => <div className="card" key={item}><span className="kicker">0{index + 1}</span><h2>{item.replaceAll("-", " ")}</h2><Link className="textLink" href={`/lab/${item}`}>Open module â†’</Link></div>)}</div></section></main></>;
    if (!labModules.includes(labModule as (typeof labModules)[number])) notFound();
    let content: React.ReactNode;
    if (labModule === "deployments") content = <><PageHero eyebrow="Deployments" title="Deployment context without exposing Production internals." lede="Use Vercel as the source of truth for environment and deployment state." /><section className="section"><div className="shell grid two"><div className="card"><span className="kicker">Environment</span><h2>{env}</h2><p>{production ? "Detailed deployment identifiers are intentionally hidden in Production." : `Deployment ID: ${process.env.VERCEL_DEPLOYMENT_ID || "not available"}`}</p></div><div className="card"><span className="kicker">Git</span><h2>Repository status</h2><p>Git metadata should be read from the platform integration rather than invented in application UI.</p></div></div></section></>;
    else if (labModule === "observability") content = <><PageHero eyebrow="Observability" title="Generate controlled runtime signals." lede="Safe status probes remain available while intentional Production 500 generation is blocked." /><section className="section"><div className="shell"><StatusTools production={production} /></div></section></>;
    else if (labModule === "preview-production") content = <><PageHero eyebrow="Preview vs Production" title="The environment should change behavior, not just labels." lede="Preview is visibly marked. Production removes the banner and locks unsafe tooling." /><section className="section"><div className="shell grid two"><div className="card"><span className="kicker">Current environment</span><h2>{env}</h2><p>{production ? "Production presentation is clean and unsafe test tools are restricted." : "Preview is explicitly labeled so test traffic is never mistaken for Production."}</p></div><div className="card"><span className="kicker">Release policy</span><h2>Preview first</h2><p>Build, inspect real behavior, then promote only after quality gates pass.</p></div></div></section></>;
    else if (labModule === "environment") content = <><PageHero eyebrow="Environment Variables" title="Show enough context to learn, not enough to leak." lede="Environment data is intentionally bounded in Production." /><section className="section"><div className="shell data"><div className="row"><span>VERCEL_ENV</span><strong>{env}</strong></div><div className="row"><span>VERCEL_REGION</span><strong>{process.env.VERCEL_REGION || "not available"}</strong></div><div className="row"><span>Deployment context</span><strong>{production ? "sensitive context hidden" : process.env.VERCEL_URL || "not available"}</strong></div></div></section></>;
    else if (labModule === "feature-flags") { const flags = featureFlags(); content = <><PageHero eyebrow="Feature Flags" title="Defaults should fail safe." lede="Flags come from explicit environment values or documented release policy." /><section className="section"><div className="shell grid three">{Object.entries(flags).map(([name, flag]) => <div className="card" key={name}><span className="kicker">{flag.enabled ? "ON" : "OFF"}</span><h2>{name}</h2><p>{flag.source}</p></div>)}</div></section></>; }
    else if (labModule === "performance") content = <><PageHero eyebrow="Performance" title="Observe the cache behavior Vercel actually returns." lede="The probe reports response headers instead of pretending every request has the same cache state." /><section className="section"><div className="shell specGrid"><div className="card"><span className="kicker">How to read it</span><h2>MISS can be correct.</h2><p>The first request may be a MISS. Repeat requests can produce different edge cache headers or age values as the response is reused.</p></div><div className="card"><PerformanceProbe /></div></div></section></>;
    else content = <><PageHero eyebrow="Error Handling" title="Test failure paths without giving Production a self-destruct button." lede="Preview self-tests are available while sensitive testing is blocked in Production." /><section className="section"><div className="shell"><SelfTest production={production} /></div></section></>;
    return <><LabNav /><main id="main-content">{content}</main></>;
  }

  notFound();
}

